{
 "title": "ONGuard",
 "tags": [
  "trusted-content",
  "exhort",
  "onguard"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": "exhort-stage,exhort-production" },
   { "name": "CloudWatch_Datasource", "query": "cloudwatch" },
   {
    "name": "CacheClusterID",
    "label": "CacheClusterID",
    "query": "exhort-elasticache-stage-001,exhort-elasticache-stage-002"
   }
  ]
 },
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"${namespace}\", container=\"app\", pod=~\"onguard.+\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"${namespace}\", container=\"app\", pod=~\"onguard.+\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "topk(1, kube_pod_container_resource_limits{namespace=\"${namespace}\", container=\"app\",resource=\"memory\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"${namespace}\", pod=~\"onguard.+\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"${namespace}\", pod=~\"onguard.+\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Elasticache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "CacheItems",
     "type": "stat",
     "description": "The number of items in the cache",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "label": "CacheItemsCurrItemsCacheHitRate",
       "metricQueryType": 1,
       "namespace": "AWS/ElastiCache",
       "queryMode": "Metrics",
       "region": "default",
       "sql": {
        "from": { "property": { "name": "AWS/ElastiCache", "type": "string" }, "type": "property" },
        "select": {
         "name": "AVG",
         "parameters": [
          { "name": "CurrItems", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "where": {
         "expressions": [
          { "operator": { "name": "=", "value": "$CacheClusterID" }, "property": { "name": "CacheClusterId", "type": "string" }, "type": "operator" }
         ],
         "type": "and"
        }
       },
       "sqlExpression": "SELECT AVG(CurrItems) FROM \"AWS/ElastiCache\" WHERE CacheClusterId = '$CacheClusterID'",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "DatabaseMemoryUsagePercentage",
     "type": "stat",
     "description": "Percentage of the memory for the cluster that is in use",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "label": "CacheItemsCurrItemsCacheHitRate",
       "metricQueryType": 1,
       "namespace": "AWS/ElastiCache",
       "queryMode": "Metrics",
       "region": "default",
       "sql": {
        "from": { "property": { "name": "AWS/ElastiCache", "type": "string" }, "type": "property" },
        "select": {
         "name": "AVG",
         "parameters": [
          { "name": "DatabaseMemoryUsagePercentage", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "where": {
         "expressions": [
          { "operator": { "name": "=", "value": "$CacheClusterID" }, "property": { "name": "CacheClusterId", "type": "string" }, "type": "operator" }
         ],
         "type": "and"
        }
       },
       "sqlExpression": "SELECT AVG(DatabaseMemoryUsagePercentage) FROM \"AWS/ElastiCache\" WHERE CacheClusterId = '$CacheClusterID'",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "CacheHitRate",
     "type": "timeseries",
     "description": "Indicates the usage efficiency of the Redis instance. If the cache ratio is lower than about 0.8, it means that a significant amount of keys are evicted, expired, or don't exist",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "label": "CacheHitRate",
       "metricQueryType": 1,
       "namespace": "AWS/ElastiCache",
       "queryMode": "Metrics",
       "region": "default",
       "sql": {
        "from": { "property": { "name": "AWS/ElastiCache", "type": "string" }, "type": "property" },
        "select": {
         "name": "AVG",
         "parameters": [
          { "name": "CacheHitRate", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "where": {
         "expressions": [
          { "operator": { "name": "=", "value": "$CacheClusterID" }, "property": { "name": "CacheClusterId", "type": "string" }, "type": "operator" }
         ],
         "type": "and"
        }
       },
       "sqlExpression": "SELECT AVG(CacheHitRate) FROM \"AWS/ElastiCache\" WHERE CacheClusterId = '$CacheClusterID'",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "BytesUsedForCache",
     "type": "timeseries",
     "description": "The total number of bytes allocated by Redis for all purposes, including the dataset, buffers, and so on.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "label": "BytesUsedForCache ",
       "metricQueryType": 1,
       "namespace": "AWS/ElastiCache",
       "queryMode": "Metrics",
       "region": "default",
       "sql": {
        "from": { "property": { "name": "AWS/ElastiCache", "type": "string" }, "type": "property" },
        "select": {
         "name": "AVG",
         "parameters": [
          { "name": "BytesUsedForCache", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "where": {
         "expressions": [
          { "operator": { "name": "=", "value": "$CacheClusterID" }, "property": { "name": "CacheClusterId", "type": "string" }, "type": "operator" }
         ],
         "type": "and"
        }
       },
       "sqlExpression": "SELECT AVG(BytesUsedForCache) FROM \"AWS/ElastiCache\" WHERE CacheClusterId = '$CacheClusterID'",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Evictions",
     "type": "stat",
     "description": "The number of keys that have been evicted due to the maxmemory limit",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "label": "CacheItemsCurrItemsCacheHitRate",
       "metricQueryType": 1,
       "namespace": "AWS/ElastiCache",
       "queryMode": "Metrics",
       "region": "default",
       "sql": {
        "from": { "property": { "name": "AWS/ElastiCache", "type": "string" }, "type": "property" },
        "select": {
         "name": "AVG",
         "parameters": [
          { "name": "Evictions", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "where": {
         "expressions": [
          { "operator": { "name": "=", "value": "$CacheClusterID" }, "property": { "name": "CacheClusterId", "type": "string" }, "type": "operator" }
         ],
         "type": "and"
        }
       },
       "sqlExpression": "SELECT AVG(Evictions) FROM \"AWS/ElastiCache\" WHERE CacheClusterId = '$CacheClusterID'",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "DatabaseCapacityUsagePercentage",
     "type": "stat",
     "description": "Percentage of the total data capacity for the cluster that is in use",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "label": "CacheItemsCurrItemsCacheHitRate",
       "metricQueryType": 1,
       "namespace": "AWS/ElastiCache",
       "queryMode": "Metrics",
       "region": "default",
       "sql": {
        "from": { "property": { "name": "AWS/ElastiCache", "type": "string" }, "type": "property" },
        "select": {
         "name": "AVG",
         "parameters": [
          {
           "name": "DatabaseCapacityUsagePercentage",
           "type": "functionParameter"
          }
         ],
         "type": "function"
        },
        "where": {
         "expressions": [
          { "operator": { "name": "=", "value": "$CacheClusterID" }, "property": { "name": "CacheClusterId", "type": "string" }, "type": "operator" }
         ],
         "type": "and"
        }
       },
       "sqlExpression": "SELECT AVG(DatabaseCapacityUsagePercentage) FROM \"AWS/ElastiCache\" WHERE CacheClusterId = '$CacheClusterID'",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "Elasticache host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPUUtilization",
     "type": "timeseries",
     "description": "The percentage of CPU utilization for the entire host",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "label": "CPUUtilization",
       "metricQueryType": 1,
       "namespace": "AWS/ElastiCache",
       "queryMode": "Metrics",
       "region": "default",
       "sql": {
        "from": { "property": { "name": "AWS/ElastiCache", "type": "string" }, "type": "property" },
        "select": {
         "name": "AVG",
         "parameters": [
          { "name": "CPUUtilization", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "where": {
         "expressions": [
          { "operator": { "name": "=", "value": "$CacheClusterID" }, "property": { "name": "CacheClusterId", "type": "string" }, "type": "operator" }
         ],
         "type": "and"
        }
       },
       "sqlExpression": "SELECT AVG(CPUUtilization) FROM \"AWS/ElastiCache\" WHERE CacheClusterId = '$CacheClusterID'",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "FreeableMemory",
     "type": "timeseries",
     "description": "The amount of free memory available on the host",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "label": "FreeableMemory",
       "metricQueryType": 1,
       "namespace": "AWS/ElastiCache",
       "queryMode": "Metrics",
       "region": "default",
       "sql": {
        "from": { "property": { "name": "AWS/ElastiCache", "type": "string" }, "type": "property" },
        "select": {
         "name": "AVG",
         "parameters": [
          { "name": "FreeableMemory", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "where": {
         "expressions": [
          { "operator": { "name": "=", "value": "$CacheClusterID" }, "property": { "name": "CacheClusterId", "type": "string" }, "type": "operator" }
         ],
         "type": "and"
        }
       },
       "sqlExpression": "SELECT AVG(FreeableMemory) FROM \"AWS/ElastiCache\" WHERE CacheClusterId = '$CacheClusterID'",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "SwapUsage",
     "type": "timeseries",
     "description": "The amount of swap used on the host.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "label": "SwapUsage",
       "metricQueryType": 1,
       "namespace": "AWS/ElastiCache",
       "queryMode": "Metrics",
       "region": "default",
       "sql": {
        "from": { "property": { "name": "AWS/ElastiCache", "type": "string" }, "type": "property" },
        "select": {
         "name": "AVG",
         "parameters": [
          { "name": "SwapUsage", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "where": {
         "expressions": [
          { "operator": { "name": "=", "value": "$CacheClusterID" }, "property": { "name": "CacheClusterId", "type": "string" }, "type": "operator" }
         ],
         "type": "and"
        }
       },
       "sqlExpression": "SELECT AVG(SwapUsage) FROM \"AWS/ElastiCache\" WHERE CacheClusterId = '$CacheClusterID'",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "EngineCPUUtilization",
     "type": "timeseries",
     "description": "Provides CPU utilization of the Redis engine thread",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "label": "EngineCPUUtilization",
       "metricQueryType": 1,
       "namespace": "AWS/ElastiCache",
       "queryMode": "Metrics",
       "region": "default",
       "sql": {
        "from": { "property": { "name": "AWS/ElastiCache", "type": "string" }, "type": "property" },
        "select": {
         "name": "AVG",
         "parameters": [
          { "name": "EngineCPUUtilization", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "where": {
         "expressions": [
          { "operator": { "name": "=", "value": "$CacheClusterID" }, "property": { "name": "CacheClusterId", "type": "string" }, "type": "operator" }
         ],
         "type": "and"
        }
       },
       "sqlExpression": "SELECT AVG(EngineCPUUtilization) FROM \"AWS/ElastiCache\" WHERE CacheClusterId = '$CacheClusterID'",
       "statistic": "Average"
      }
     ]
    }
   ]
  }
 ]
}